[package]
name = "enchantron-core"
version = "0.1.0"
authors = ["Kevin Guthrie <kevin.guthrie@gmail.com>"]
edition = "2018"
#build = "build/build.rs"


[dependencies]
futures = "0.1.27"
rayon = "1.0.3"
crossbeam-channel = "0.3.8"
trace-error = "0.1.5"
lazy_static = "1.3.0"
log = "0.4"
simplelog = "0.5.3"
itertools = "0.8.0"
getset = "0.0.7"
derive_builder = "0.7.1"
nom = "4.2.3"
statrs = "0.11.0"
num = "0.2.0"
cached = "0.8.0"
chashmap = "2.2.2"
atomic-counter = "1.0.1"
fnv = "1.0.6"

[build-dependencies]
cbindgen = "0.8.6"
regex = "1.1.6"
lazy_static = "1.3.0"
handlebars = "1.1.0"
serde = "1.0.91"
serde_derive = "1.0.91"
serde_json = "1.0.39"
heck = "0.3.1"
derive_builder = "0.7.1"
itertools = "0.8.0"
log = "0.4"
simplelog = "0.5.3"

[lib]
name = "enchantron"
path = "src/lib.rs"
crate-type = ["staticlib"]

