[package]
name = "enchantron-core"
version = "0.1.0"
authors = ["Kevin Guthrie <kevin.guthrie@gmail.com>"]
edition = "2018"
build = "build/build.rs"


[dependencies]
trace-error = "0.1.5"
lazy_static = "1.4.0"
log = "0.4"
simplelog = "0.7.4"
itertools = "0.8.2"
getset = "0.0.9"
derive_builder = "0.9.0"
nom = "5.0.1"
atomic-counter = "1.0.1"
twox-hash = "1.5.0"
anymap = "0.12.1"
tokio = { version = "0.2.9", features = [ "time", "sync", "rt-threaded", "rt-core", "stream" ] }
futures = "0.3.1"
async-std = "1.4.0"
async-trait = "0.1.22"
png = "0.15.3"
rand = "0.7.3"

[build-dependencies]
cbindgen = "0.8.6"
regex = "1.1.6"
lazy_static = "1.3.0"
handlebars = "1.1.0"
serde = "1.0.91"
serde_derive = "1.0.91"
serde_json = "1.0.39"
heck = "0.3.1"
derive_builder = "0.7.1"
itertools = "0.8.0"
log = "0.4"
simplelog = "0.5.3"

[lib]
name = "enchantron"
path = "src/lib.rs"
crate-type = ["staticlib"]

