[package]
name = "enchantron-core"
version = "0.1.0"
authors = ["Kevin Guthrie <kevin.guthrie@gmail.com>"]

[dependencies]
parallel-event-emitter = "0.2.4"
futures = "0.1.8"
rayon = "1.0.1"
crossbeam-channel = "0.2.2"
trace-error = "0.1.3"
lazy_static = "1.0"

[build-dependencies]
cbindgen = "0.6.0"
regex = "1.0.2"

[lib]
name = "enchantron"
path = "src/lib_apple.rs"
crate-type = ["staticlib"]

[[bin]]
name = "enchantron-rust"
path = "src/main.rs"
